### ISSUE TITLE
Create release branches for PHP 5 and PHP7

### ISSUE THREAD

**Issue by castamir** [Joseki/PdfResponse#10]
- [x] create branches (v3.0 for version 3 and keep master for version 4)
- [x] composer - create branch alias
- [x] composer - min stability php7 for php7 branch
- [x] fix php7 compatibility
- [ ] upgrade to php7 syntax and features

**Comment by camohub** [comment]
Same probleme here.

**Comment by honzarac** [comment]
Please can you resolve problem with PHP 7.1?

mpdf/mpdf suports PHP 7.1 from version 7 and now is release beta2

Thanks

**Comment by castamir** [comment]
I'll try to look at it this week, ok?

**Comment by castamir** [comment]
I've added support for php7.1. By doing that, mpdf 6.1.3 is a new minimum required version (there was a bug that fixed incompatibility with php7.1).

Support for beta versions is not a good idea. I'll add support for mpdf 7 after its final release.

**Comment by JanGalek** [comment]
mpdf 6.1.3 has problem with php 7.1

![image](https://user-images.githubusercontent.com/13171542/28670782-7f41839e-72da-11e7-9b08-fd89cd4a6552.png)

**Comment by castamir** [comment]
@JanGalek could you please create a test or describe in detail how to reproduce this error?

**Comment by JanGalek** [comment]
yes, when I add css:

```
$pdfResponse->getMPDF()->WriteHTML($this->getCss(), 1); // or withou 1 and with tag style
```

**Comment by JanGalek** [comment]
My bad, I use in css:
```
vertical-align: middle;
```

**Comment by castamir** [comment]
so is it ok now or what?

**Comment by JanGalek** [comment]
@castamir yes, its ok, sorry

**Comment by Stopka** [comment]
mPdf 7 is out now with support up to php 7.2

**Comment by castamir** [comment]
It would be very nice from you guys, if you try to do some things by yourself. For example you can create a pull request. It will make things faster for everyone.

**Comment by petrparolek** [comment]
Is it still actual issue @camohub ? If yes I will look at it

**Comment by camohub** [comment]
@petrparolek use MPDF instead.

**Comment by petrparolek** [comment]
Closing this issue, because of inactivity. Feel free to reopen.
