### ISSUE TITLE
Remove .git

### ISSUE THREAD

**Issue by spernica** [Joseki/PdfResponse#11]
Please remove .git folder from your repository, it's making a mess when I try your project with composer and Nette.

The problem is that I versioned folder vendor and your files are already shows as commited.

**Comment by castamir** [comment]
You are probably installing PdfResponse like this:

```
    "require": {
        "joseki/pdf-response": "@dev"
    },
```

Try stable release using this

```
    "require": {
        "joseki/pdf-response": "~2.0"
    },
```

If it doesn't help, try remove joseki/pdf-response from your vendor and install it again using previous settings or using `--preder-dist` argument from command line
