### ISSUE TITLE
mPDF 5.7.4

### ISSUE THREAD

**Issue by romanmatyus** [Joseki/PdfResponse#13]
Hello, why it's version of mPDF 5.7.4 disabled in composer?
mPDF 5.7.3 it's not compatible with PHP 7.

**Comment by castamir** [comment]
Hi, because v5.7.4 contains many BC breaks. 
It would be best to create a new major version of PdfResponse compatible with php7 and stable version of mPDF that is also compatible with php7

**Comment by castamir** [comment]
feel free to try 3.0.0 beta https://github.com/Joseki/PdfResponse/releases/tag/v3.0.0-beta
