### ISSUE TITLE
Use of mpdf/mpdf 6.*

### ISSUE THREAD

**Issue by Lexinek** [Joseki/PdfResponse#14]

**Comment by doliadu** [comment]
I am using mpdf:6.1.2 and yours dev-master and it works fine.

**Comment by castamir** [comment]
I've got a font issue with Adobe right now. Not sure if the problem is in mpdf or somewhere else...

**Comment by castamir** [comment]
feel free to try 3.0.0 beta https://github.com/Joseki/PdfResponse/releases/tag/v3.0.0-beta

**Comment by Lexinek** [comment]
Thank you! Will do so.

**Comment by castamir** [comment]
try 3.0.0-beta.2 please (https://github.com/Joseki/PdfResponse/releases/tag/v3.0.0-beta.2)
