### ISSUE TITLE
No option to use underscopes instead of dashes in filename

### ISSUE THREAD

**Issue by GEp1c** [Joseki/PdfResponse#16]
Would be nice to have option to replace dashes with underscores or vice-versa while saving PDF with `save` method. Because filename is webalized everytime (which is good), but other systems (for example in my case) accept only pdf's with underscores in filename.

**Comment by castamir** [comment]
@GEp1c hi, you probably mean underscores, right?

method `save($dir, $filename = null)` allows you to save a file. For internal reasons, the name of the file will be webalized. If you want to change dashes to underscores, then you can do it by yourself - call `String::webalize($filename)` by yourself and then replace dashes with underscores and after that call `save()`.

**Comment by GEp1c** [comment]
The problem is, that your webalize will then replace underscores with dashes back and there is no posibility to change this behaviour. I had to override your save method in my extended class, but it's not what I wanted.

**Comment by GEp1c** [comment]
@castamir Thank you very much!! And sorry for that late response!
