### ISSUE TITLE
Non working css rows 

### ISSUE THREAD

**Issue by Isigar** [Joseki/PdfResponse#19]
Hi, 
I want to create PDF from latte template with boostrap template and i have little problem with this error:` A non-numeric value encountered` That will be fine but i discovered bigger problem that pdf don't create rows and column in good way http://prntscr.com/grhgn6
That is PDF export and it should looked like this http://prntscr.com/grhh5w

**Comment by castamir** [comment]
check https://github.com/Joseki/PdfResponse/issues/10#issuecomment-318351666 - same error message mentioned. 

To check, if it is really problem of this library, please try to reproduce it. For example try to generate html output a put it directly into mPDF and see the output. If the output still looks bad, then it is probably mPDF's issue. It may not support all css rules.

If this not the case, I need something to work with, something I can reproduce by myself. Can you do this?

**Comment by Isigar** [comment]
I will try to resolve this problem and I will let you know.

Dne 30.9.2017 15:21 napsal uživatel "Miroslav Paulík" <
notifications@github.com>:

**Comment by petrparolek** [comment]
Is it still actual issue @Isigar ?

**Comment by Isigar** [comment]
@petrparolek not at all, i am not using this library anymore.

**Comment by petrparolek** [comment]
Closing this issue, because of inactivity. Feel free to reopen.
