### ISSUE TITLE
Config tempDir for mPdf

### ISSUE THREAD

**Issue by romanmatyus** [Joseki/PdfResponse#22]
The folder should be set to nette cache.

![image](https://user-images.githubusercontent.com/1110294/36204237-c927adea-118a-11e8-8ac9-5396c36eece5.png)

**Comment by castamir** [comment]
As far as I remember, this was an issue in old version of mPDF itself. It wasn't configurable by then.

**Comment by romanmatyus** [comment]
Now it's possible configure `tempDir` only when I create mPdf instance manualy, but not when I create mPdf through [PdfResponse factory](https://github.com/Joseki/PdfResponse/blob/master/src/Joseki/Application/Responses/PdfResponse.php#L443). True?

**Comment by KazuAlex** [comment]
Why do not use the [sys_get_temp_dir()](https://www.php.net/manual/en/function.sys-get-temp-dir.php) function ? It's better to avoid these kinds of problems

**Comment by castamir** [comment]
you should ask the authors of mpdf, not here. PdfResponse is a wrapper over mpdf and nette

**Comment by petrparolek** [comment]
Is it still actual issue @romanmatyus ?

**Comment by petrparolek** [comment]
Closing this issue, because of inactivity. Feel free to reopen.

**Comment by lukyrys** [comment]
Yes, problem persist. PDFResponse needs settings temp dir for mpdf..
Last version of package.. 
```
Mpdf\MpdfException
Temporary files directory "/var/www/..../vendor/mpdf/mpdf/src/Config/../../tmp" is not writable
```

**Comment by petrparolek** [comment]
I wiil look at it

**Comment by petrparolek** [comment]
@lukyrys could you test my PR #35 please?

**Comment by petrparolek** [comment]
merged
