### ISSUE TITLE
PHP 7.2 Support stable?

### ISSUE THREAD

**Issue by RomanHodulak** [Joseki/PdfResponse#24]
I'd like to use this library in a PHP 7.2 project. When will the PHP 7.2 support, that is currently in `master`, be released as stable? Is there anything preventing it?

**Comment by castamir** [comment]
@RomanHodulak here is currently one open pull request https://github.com/Joseki/PdfResponse/pull/23

I wanted cleanup the code as well, but I might release stable even without cleanup. I'll try to take a look at it during this weekend, is it ok for you?

**Comment by RomanHodulak** [comment]
@castamir Awesome, thank you.

**Comment by RomanHodulak** [comment]
@castamir Hello, I'd like to just check back, any updates on this issue?

**Comment by lupo112** [comment]
Hi, any news? Is this in progress or something?

**Comment by petrparolek** [comment]
I added support of 7.4 (supported PHP versions are 7.1, 7.2, 7.3 and 7.4
