### ISSUE TITLE
Page format as array

### ISSUE THREAD

**Issue by JKoty** [Joseki/PdfResponse#28]
MPDF allows to set page format as array, but the `setPageFormat()` function in PdfResponse has strict type of string.

Expected:
`$pdf->setPageFormat([99, 210]); //is OK`

Result:
Exception.

**Comment by JKoty** [comment]
Fix in pull request #27

**Comment by petrparolek** [comment]
Is it still actual issue @JKoty ?

**Comment by JKoty** [comment]
> Is it still actual issue @JKoty ?

Yup. I use my fork.

**Comment by petrparolek** [comment]
PR was merged
