### ISSUE TITLE
displayPreferences property missing

### ISSUE THREAD

**Issue by premekkoch** [Joseki/PdfResponse#9]
I miss possibility to set "NoPrintScaling" value in mPdf. Can you add new property with propagation to mPdf to your class to enable this setting?  
http://mpdf1.com/manual/index.php?tid=389&searchstring=displayPreferences

Tnx, Premek

**Comment by castamir** [comment]
You can access to mPdf instance when calling [getMpdf()](https://github.com/Joseki/PdfResponse/blob/master/src/Joseki/Application/Responses/PdfResponse.php#L270)

**Comment by premekkoch** [comment]
Oh, in this case sorry about this issue (my first one) and thanks a lot for this nice addon. Have a nice weekend. Premek
